name: Update metadata retrieved from geocat


on:
  push:
    branches:
      - main

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update metadata
        # Not working because this script currently needs a qgis instance
        run: |
          cd swissgeodownloader/scripts
          ./datageoadmin_catalog_analysis.py refreshMetadata

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Automated update of geocat metadata
          title: Automated update of geocat metadata
          body:
          branch: update-layers
