name: Workflow and package test

on:
  push:
    branches:
      - dev

jobs:
  workflow-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: copy readme, license and changelog
        run: |
          cp README.md swissgeodownloader/README.md
          cp LICENSE swissgeodownloader/LICENSE
          cp CHANGELOG.md swissgeodownloader/CHANGELOG.md

      - name: Package
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=0.0.0
          qgis-plugin-ci package ${VERSION}

      - uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: swissgeodownloader_dev
          path: swissgeodownloader.0.0.0.zip
          if-no-files-found: error
